# Render Configuration for 4regab.me AI Tools Backend

services:
  - type: web
    name: 4regab-ai-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run server:build
    startCommand: npm run server:start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: GEMINI_API_KEY
        sync: false # Set this manually in Render dashboard from Google AI Studio
      - key: PORT
        value: 10000
    scaling:
      minInstances: 1
      maxInstances: 2
    autoDeploy: true
    branch: main
